{% set version = "1.3.0" %}
{% set sha256 = "c9e18aefed3828c2ee1d0eecd3951bfccd9b28b7b6502fd827626b9c0d16b686" %}

package:
  name: quartet
  version: "{{version}}"

source:
  url: https://github.com/aaranyue/quarTeT/archive/refs/tags/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - minimap2
    - unimap
    - mummer4
    - trf
    - cd-hit
    - blast
    - tidk
    - gnuplot
    - r-base
    - r-rideogram
    - r-ggplot2

test:
  imports:
    - quartet
  commands:
    - quartet --help

about:
  home: https://github.com/aaranyue/quarTeT
  license: MIT
  summary: "A telomere-to-telomere toolkit for gap-free genome assembly and centromeric repeat identification"
  